FROM composer:2.0 as step0

ARG TESTING=false
ENV TESTING=$TESTING

WORKDIR /usr/local/src/

COPY composer.lock /usr/local/src/
COPY composer.json /usr/local/src/

RUN composer update --ignore-platform-reqs --optimize-autoloader \
    --no-plugins --no-scripts --prefer-dist
    
FROM appwrite/utopia-base:php-8.3-0.1.0 as final

ENV PHP_MEMCACHED_VERSION=v3.2.0

LABEL maintainer="team@appwrite.io"

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN \
  apk update \
  && apk add --no-cache make automake autoconf g++ gcc zlib-dev libmemcached-dev \
  && rm -rf /var/cache/apk/*
    

RUN echo extension=redis.so >> /usr/local/etc/php/conf.d/redis.ini


RUN \
  # Memcached Extension
  git clone --branch $PHP_MEMCACHED_VERSION https://github.com/php-memcached-dev/php-memcached.git && \
  cd php-memcached && \
  phpize && \
  ./configure && \
  make && make install && \
  cd ..

RUN echo extension=memcached.so >> /usr/local/etc/php/conf.d/memcached.ini

WORKDIR /usr/src/code

# Add Source Code
COPY ./ /usr/src/code

COPY --from=step0 /usr/local/src/vendor /usr/src/code/vendor

CMD [ "tail", "-f", "/dev/null" ]
